"""
Fibonacci numbers are generated by setting F0 = 0, F1 = 1, and then using the formula:
Your task is to efficiently calculate the nth element in the Fibonacci sequence
and then count the occurrence of each digit in the number.
Return a list of integer pairs sorted in descending order.
"""

from collections import Counter

def fib_digits(n):
    a, b = 0, 1
    for _ in range(n): a, b = b, a+b
    return sorted(((b, int(a)) for a, b in Counter(str(a)).items()), reverse=True)